In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import ipaddress
from datetime import datetime
import time
import keras
import re
from sklearn import preprocessing

C:\Users\ASUS\Anaconda3\envs\tensorflow-gpu\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [29]:
data = pd.read_csv("./data_full.csv", sep = ";", error_bad_lines=False)

b'Skipping line 10780784: expected 10 fields, saw 11\nSkipping line 10793876: expected 10 fields, saw 11\n'
b'Skipping line 10821923: expected 10 fields, saw 11\n'
C:\Users\ASUS\Anaconda3\envs\tensorflow-gpu\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [28]:
catalog = pd.read_csv("./catalog.csv", sep = ";", error_bad_lines=False)

In [4]:
data.head()

timestamp              ip  track_id                            cookie  \
0  1517778000   230.59.74.120  10912114  42536dc7a8578b0cfac05f704977429a   
1  1517778000  218.222.225.36  10885813  8f92f3f2b1e7a2498761b8cb3b1d03c3   
2  1517778000   55.63.241.224   6948236  336d5ebc5436534e61d16e63ddfca327   
3  1517778000    230.34.98.99   8481402  cf8dd809edf104873a1c57921b34f25e   
4  1517778000    232.3.41.226  10908060  4ca525a1d60de6d74e3c32529fe47ab5   

  live       user_id                                            referer  \
0    0           NaN  https%3A%2F%2Frutube.ru%2Fvideo%2F0f5c9c5839b1...   
1    0           NaN  https%3A%2F%2Frutube.ru%2Fvideo%2Fd8068436dcf5...   
2    -  2.231332e+09                  http%3A%2F%2Fandroid.rutube.ru%2F   
3    0           NaN  https%3A%2F%2Frutube.ru%2Fvideo%2F1058cf249e46...   
4    0           NaN  https%3A%2F%2Fyastatic.net%2Fvideo-player%2F0x...   

                                              uagent rightholder author_id  
0  Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...           2   1480930  
1  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.3...           2    301323  
2                                       okhttp/2.6.0           -         -  
3  Mozilla/5.0 (Linux; Android 7.1.2; Redmi 4X Bu...         NaN    721346  
4  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...         135    599848

In [5]:
catalog.head()

idec  track_id                          video_id     series_id  \
0  PR592505  10258734  cd59084eb50e6ebe9fe20ad04e0c17db  1.045685e+10   
1  PR609630  10843255  a5d2e6bae4752d9ec0fae9b53f00700d  1.059247e+10   
2  PR597128  10573153  bcd45606c1f7cbb5cb9d1dbd7d346cc3  1.047956e+10   
3  PR257331   6617650  609217ac7b8c4e55d44c4a29bf52554b           NaN   
4  PR529698   7991493  bde3620ba038b3e8dd41d03bf516a7eb  1.024102e+10   

                                  title  season  episode  episode_global  \
0  \tБыть или не быть, 1 сезон, 1 серия     1.0      1.0             1.0   
1                                   NaN    11.0      1.0             1.0   
2                                   NaN     7.0      1.0             1.0   
3            "Интерны. История болезни"     NaN      NaN             NaN   
4                          #ЖАННАПОЖЕНИ     1.0      1.0           101.0   

             date_efir  duration  
0  02.04.2017 22:00:34       NaN  
1                  NaN       NaN  
2  06.09.2017 22:46:05       NaN  
3  12.06.2012 22:00:44       NaN  
4  05.09.2015 13:30:00       NaN

In [6]:
def add_device(df):
    regexpDesktop = re.compile('(Windows|Linux|Mozilla)')
    regexpMobile = re.compile('(iPhone|RutubeAndroid|okhttp|CFNetwork|UCBrowser)')
    regexpTablet = re.compile('(iPad)')
    
    df['device'] = pd.Series('0', index=df.index)
    
    for i, row in df.iterrows():
        try:
            if regexpDesktop.search(df['uagent'].iloc[i]):
                df['device'][i] = 'desktop'
            elif regexpMobile.search(df['uagent'].iloc[i]):
                df['device'][i] = 'mobile'
            elif regexpTablet.search(df['uagent'].iloc[i]):
                df['device'][i] = 'mobile'
        except:
            pass
            
    return df

In [7]:
def mergeData(data1, data2, field):
    data1[field] = pd.to_numeric(data1[field], errors = 'coerce')
    data2[field] = pd.to_numeric(data2[field], errors = 'coerce')
    return pd.merge(data1, data2, left_on=field, right_on=field)

In [8]:
def convIpToNumber(data):
    return data.apply(lambda x: int(ipaddress.IPv4Address(x)))

In [9]:
def applyDate(x):
    try:
        data = time.strptime(x, "%d.%m.%Y %H:%M:%S")
        return int(time.mktime(data))
    except:
        return 1e-6

In [10]:
def confDateStringToTimestamp(data):
    return data.apply(lambda x: applyDate(x))

In [42]:
def filter_users_with_n_views(data, user_column = "ip", seq_len = 4):
    by_user = data.groupby(user_column)
    by_user = by_user.filter(lambda x: len(x) >= seq_len)
    return by_user

def extract_sequences_by_user(data, user_column = "ip"):
    return data.groupby(user_column)

In [37]:
def filter_videos_than_n_views(data, n = 1000):
    data["track_id"] = pd.to_numeric(data["track_id"], errors = 'coerce', downcast = 'integer')
    data = data[data["track_id"].notnull()]
    data_top_n = data.groupby("track_id").filter(lambda x: len(x) >= n)
    return data_top_n

In [30]:
data['ip'] = convIpToNumber(data['ip'])

In [38]:
data_top_n = filter_videos_than_n_views(data)
print(len(data_top_n))

7142931


In [43]:
prepared = filter_users_with_n_views(data_top_n)
print(len(prepared))

4903997


In [26]:
def label_encoder(data):
    le = preprocessing.LabelEncoder()
    le.fit(data)
    return le

In [40]:
prepared.head(50)

timestamp          ip    track_id                            cookie  \
0    1517778000  3862645368  10912114.0  42536dc7a8578b0cfac05f704977429a   
1    1517778000  3672039716  10885813.0  8f92f3f2b1e7a2498761b8cb3b1d03c3   
4    1517778000  3892521442  10908060.0  4ca525a1d60de6d74e3c32529fe47ab5   
5    1517778000   929300702  10912230.0  0cc973c79fe7540052da1bed3c83b55b   
6    1517778000   165491643  10912230.0  40212c8fe37bae13f80ffb78c0560812   
12   1517778000   938789414  10906545.0  56cdf26f4ab3a341c15fd390f79ba5a0   
13   1517778000  2575446723  10911505.0  51631be84bc91958527f58ffdaac5e13   
16   1517778000   130821200  10912230.0  9c71ccde2228a01ef9e12b2110df4bc1   
19   1517778000  1605666730  10601176.0  b4d0c08442cd6cf33098edca962870b3   
23   1517778000    75597478  10795672.0  29ec8d46d11dfbb8046ad4a1a3c4fd4d   
25   1517778000  3317797127  10830184.0  aac6347467d45ed513f1ba4b956a3f78   
29   1517778000    98208975  10885813.0  a71febb727f41264e0b294af0d09caa6   
30   1517778000  3895499260  10912230.0  eeedeb456410b9e9ee596372d7b93d99   
34   1517778000   926246750  10435023.0  4c40158837da3887fa5871e9004170fd   
38   1517778000  2412729518  10902309.0  24bdb52f6df1eb3f4dab95054383eaff   
42   1517778000  1160595362   7584246.0  7e2b5bf0fbbc4ed578797d1d7c547b6b   
43   1517778000  1679088066  10351051.0  0394a48417b0730064164b21a49dd8be   
50   1517778000  2412753022  10912230.0  e03a81480f3ee7b05c5a4b7173fac475   
58   1517778001  1958681658  10912919.0  f8192d268fea16bc5ac53ebb7820606a   
61   1517778001   252979459   8407951.0  7424bd5622a80a32876586595dc6058f   
62   1517778001    80892201  10910018.0  1bd02255cd30ea3fee62fc5fc61bb3a9   
67   1517778001    92494319  10908005.0  064f9c9c92695543db8c1e2ee8dd6110   
70   1517778001  2135829615  10912230.0  e1f348056d264810b912b6112f8cace5   
73   1517778001  1602016172  10610361.0  5291db72ab2a3042004563541c36978a   
80   1517778001  1602929511  10509069.0  d41d8cd98f00b204e9800998ecf8427e   
94   1517778001  3861089753  10362172.0  31190074e985c6974d31cf637fb25d87   
96   1517778001   938648305   9965327.0  2be99de2311416b326dd39610f8be21c   
97   1517778001    78260941  10793556.0  d41d8cd98f00b204e9800998ecf8427e   
101  1517778001   928428522  10362172.0  336d5ebc5436534e61d16e63ddfca327   
103  1517778001    75597320  10909487.0  336d5ebc5436534e61d16e63ddfca327   
105  1517778001   139173806   8116567.0  54a38d21347a5f7e109e3864d8394b2d   
109  1517778001  3862596465  10643476.0  52a0652f0a6369af32a7d2244fc88ee3   
112  1517778001  3865531487  10254004.0  d41d8cd98f00b204e9800998ecf8427e   
117  1517778002  3866461027   7442506.0  6535b902c9777066bdb629c6bdc6a6e7   
118  1517778002  1948537070  10235573.0  398928b23c0adbf09cf1ab2708bafd4b   
120  1517778002    21267325  10900441.0  d9f49b7e19e9c2375c5dfe159ed7a7f5   
122  1517778002   419308798   5037615.0  c600f80e01af9754d5d751d512c01a63   
124  1517778002  3450157043  10494066.0  774e48ebfa68ec96547495238719b4aa   
128  1517778002  1601905157  10885813.0  8f09f714b00a380f5b7b28a0d5a18f34   
130  1517778002   419308786  10900618.0  bb49602c824d5506cdf8aa0a8127af7e   
132  1517778002  3902917654   9946574.0  c4bf69f61c7ff6b8296563299d8cb805   
135  1517778002   409042132  10912984.0  684a254a00c317df5998fb01fe163b56   
136  1517778002   130825604   7733613.0  d41d8cd98f00b204e9800998ecf8427e   
137  1517778002  1958728946   6416313.0  8a34b05dab71663854e5be597d569844   
140  1517778002  1953112472  10912230.0  d41d8cd98f00b204e9800998ecf8427e   
141  1517778002   260439171  10912230.0  b046e4ac7a19ac76030c7dd50cc84483   
145  1517778002  3907086550  10610361.0  e5aa283f9ac55d0f4eb643d7a37fc86e   
146  1517778002    83995260  10911506.0  d41d8cd98f00b204e9800998ecf8427e   
147  1517778002  1956156926  10911505.0  d7b946fb9078717d9d1acc39f9a4ddae   
150  1517778002  2145943502  10907745.0  d41d8cd98f00b204e9800998ecf8427e   

    live       user_id                                            referer  \
0

In [44]:
track_ids = prepared["track_id"]

vocab_size = track_ids.nunique()

le = label_encoder(track_ids.values)
print(le.transform(track_ids.values[0:5]))
print(vocab_size)

[858 690 804 860 860]
955


In [16]:
def prepare_data(data, catalog):
    
    data = mergeData(data, catalog, "track_id")
    
    data['ip'] = convIpToNumber(data['ip'])
    
    data = filter_having_more_than_n_views(data)
    
    data = data.drop(['live', 'user_id', 'rightholder'], axis=1)
    
    data['date_efir'] = confDateStringToTimestamp(data['date_efir'])
    
    data = add_device(data)
    
    return data

print(prepare_data(data.head(10000), catalog))

C:\Users\ASUS\Anaconda3\envs\tensorflow-gpu\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


       timestamp          ip  track_id                            cookie  \
218   1517778098   419308798  10912114  57446605d5cca2ced09a326693ac87a7   
259   1517778121   419308784  10912114  9dccb508f8a377538ab5d12c72224654   
280   1517778134   419308798  10912114  8f5f5cfe75edb48bf15619a40ccde915   
335   1517778160   419308786  10912114  9e4b7ca438000803323c33fe0f753db0   
386   1517778006   419308786  10912230  271db70201e2f3b255fbd488a803b3a5   
482   1517778034   419308798  10912230  c9650b84635007064f5fe627770f2fe4   
707   1517778111   419308798  10912230  3ed14647c766abae8d6ede99b64eb4f3   
711   1517778112   419308784  10912230  4defd12bb8506e19fc8e279058cb8177   
836   1517778151   419308784  10912230  6bf80449eb9ac78c149cadafc42c13f0   
869   1517778160   419308786  10912230  b48bf731831e61193f1dd3e9fb21da7f   
938   1517778058   419308798  10911505  129a1f14bbca2e2f7c8d4e53e58662ea   
981   1517778121   419308784  10911505  5e0efdcb2001bca903ab424ef5d4ad1b   
1005  151777

In [60]:
def create_x_video_vectors(x, vocab_size):
    x = x["track_id"].values
    x = le.transform(x)
    x = x.astype(np.int32)
#     x = np.expand_dims(x, axis=0).astype(np.int32)
#     x = keras.utils.to_categorical(x, vocab_size)
    return x

    #     return np.repeat(np.expand_dims(x["track_id"].values, axis=0), len(x), axis = 0).reshape(len(x), len(x))

print(create_x_video_vectors(prepared.head(3), vocab_size))

def create_x(x, vocab_size):
    return create_x_video_vectors(x, vocab_size).astype(np.int32)

[858 690 804]


In [61]:
# one_hot = one_hot_encoder(prepared, "track_id", vocab_size)

def create_y(y, vocab_size):
    y = y["track_id"].values
    y = le.transform(y)
#     y = one_hot.transform(y["track_id"][y["track_id"].notnull()].values, axis = 1).toarray()
#     y = np.expand_dims(y, axis=0).astype(np.int32)
    return keras.utils.to_categorical(y, vocab_size)

print(create_y(prepared.head(3), vocab_size))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [62]:
def train_generator(seq_by_user, x_len = 3):
    for ip, group in seq_by_user:
        group = group.sort_values("timestamp")
        x = np.expand_dims(create_x(group[0:x_len], vocab_size), axis = 0)
        y = create_y(group[x_len:x_len + 1], vocab_size)
        yield (x, y)
        
generation = next(train_generator(extract_sequences_by_user(prepared)))
print(generation[0].shape)
print(generation[1].shape)
print(generation[0])
print(generation[1])

(1, 3)
(1, 955)
[[144 146 149]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

In [ ]:
# vocab_size = 248868
# print(vocab_size)

emb_input = keras.layers.Input(shape=(3,))

embedding = keras.layers.Embedding(vocab_size, 100, input_length=3)(emb_input)

avg = keras.layers.Flatten()(keras.layers.AveragePooling1D(pool_size=1)(embedding))

#input_num_cat = keras.layers.Input(shape = num_cat_shape)
#concat = keras.layers.Concat(embedding, input_num_cat)
# gru_1 = keras.layers.GRU(128, return_sequences=True)(embedding)
# gru_2 = keras.layers.GRU(128)(gru_1)
dense_1 = keras.layers.Dense(512, activation = "relu")(avg)
dense_2 = keras.layers.Dense(512, activation = "relu")(dense_1)
drop = keras.layers.Dropout(0.5)(dense_2)
dense_4 = keras.layers.Dense(vocab_size, activation = "softmax")(drop)

model = keras.models.Model(inputs=emb_input, outputs=dense_4)

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['categorical_crossentropy'])

model.summary()

model.fit_generator(train_generator(extract_sequences_by_user(prepared)), steps_per_epoch=len(prepared), epochs=1, verbose=1)



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
embedding_6 (Embedding)      (None, 3, 100)            95500     
_________________________________________________________________
average_pooling1d_4 (Average (None, 3, 100)            0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 300)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 512)               154112    
_________________________________________________________________
dense_8 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
__________